### ISSUE TITLE
Mac OS X 10.6 (Snow Leopard) support?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [brockgr/csshx#21]
```
What steps will reproduce the problem?
1. Run csshx 

What is the expected output? What do you see instead?

Can't load
'/System/Library/Perl/Extras/5.10.0/darwin-thread-multi-2level/auto/MacPerl/MacP
erl.bundle'
for module MacPerl:
/System/Library/Perl/Extras/5.10.0/darwin-thread-multi-2level/auto/MacPerl/MacPe
rl.bundle:
no appropriate 64-bit architecture (see "man perl" for running in 32-bit
mode) at
/System/Library/Perl/5.10.0/darwin-thread-multi-2level/DynaLoader.pm line 207.
 at /usr/local/bin/csshx line 237
Compilation failed in require at /usr/local/bin/csshx line 237.
BEGIN failed--compilation aborted at /usr/local/bin/csshx line 237.


What version of the product are you using? On what operating system?
csshX-0.63, Mac OS X 10.6

```

Original issue reported on code.google.com by `shan...@gmail.com` on 28 Aug 2009 at 5:50

**Comment by GoogleCodeExporter** [comment]
```
This appears to be an issue on 64bit 10.6 machines, and due to a bad build of 
perl. 
Hopefully Apple will look at this.

There are two work around:

1) EASY: Change the first line of the csshX code to be:

#!/usr/bin/perl5.8.9

This will work for 10.6 but break the script on all other platforms


2) FULL: Replace the first line with:

#!/bin/sh -- # --*-Perl-*--
# Mad perl detection for broken 64-bit 10.6.0
for p in perl5.8.9 perl; do
    if [ -x /usr/bin/$p ]; then
       exec /usr/bin/$p -x -S $0 ${1+"$@"}; fi
done
echo No valid perl found - please submit a bug at http://code.google.com/p/csshx
/issues
echo Please attach the data below:
echo --------------------
sw_vers; ls -1 /usr/bin/perl*
echo --------------------
exit 255
#!/usr/bin/perl
#line 17

This will continue to work with all 10.4+ versions and will report debug info 
if it does 
not work. (This is also at the top of the current SVN trunk version)
```

Original comment by `gavin.brock` on 28 Aug 2009 at 6:20
- Changed state: **Accepted**
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
I am working on a new version of csshX that will use the Cocoa scripting 
bridge. I will 
close this ticket when I release it..
```

Original comment by `gavin.brock` on 2 Sep 2009 at 11:55

**Comment by GoogleCodeExporter** [comment]
```
if you actually take the errors advice and look into man perl you'll find that 
it's
just the perl version compiled isn't 64 bit compatible.

adding:

export VERSIONER_PERL_PREFER_32_BIT=yes #needed for csshx to work

to your .bash_profile should fix the problem... or at least it did for me.
```

Original comment by `chadilla...@gmail.com` on 2 Oct 2009 at 1:06

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Released in 0.64: http://gavcode.wordpress.com/2010/03/30/csshx-0-64/

```

Original comment by `gavin.brock` on 30 Mar 2010 at 2:06
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
(removed previous comment, it works fine)
```

Original comment by `dario.ta...@gmail.com` on 30 Mar 2010 at 3:57

**Comment by GoogleCodeExporter** [comment]
```
Thanks gavin that works, but the line:
      exec /usr/bin/$p -x -S $0 ${1+"$@"}; fi
needs to have quotes around $0 or it will break on paths with spaces.
      exec /usr/bin/$p -x -S "$0" ${1+"$@"}; fi
Works great!
```

Original comment by `mats.tor...@gmail.com` on 31 May 2010 at 12:45

**Comment by GoogleCodeExporter** [comment]
```
@mats.tornros

Thanks for the feedback - those shell expansions are always error prone.

However, this workaround is no longer needed - the current version  will work 
fine on 10.5 and up with the 
default perl - you can get csshX 0.72 at:

http://code.google.com/p/csshx/downloads/detail?name=csshX-0.72.tgz

(Lots of other goodies and bug fixes in there too)
```

Original comment by `gavin.brock` on 31 May 2010 at 12:51
